language: python
python:
  - "3.9"
install:
  - cp contrib/env-sample .env
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source='.' manage.py test
after_success:
  coveralls